### ISSUE TITLE
Add support for the 'getrawmempool' RPC

### ISSUE THREAD

**Issue by wanglin90** [priiduneemre/btcd-cli4j#2]
hello,this client have no getrawmempool api

**Comment by priiduneemre** [comment]
Hi, yes, I am aware that some of the JSON-RPC API is still unsupported by this library. I am planning to get back to development in about a week or so (maybe a little less). I'll be sure to implement `getrawmempool` first. Cheers!

**Comment by wanglin90** [comment]
I am looking forward to it,Thank you !



wanglin20130410@gmail.com
 
From: Priidu Neemre
Date: 2016-01-18 15:33
To: priiduneemre/btcd-cli4j
CC: wanglin90
Subject: Re: [btcd-cli4j] getrawmempool (#2)
Hi, yes, I am aware that some of the JSON-RPC API is still unsupported by this library. I am planning to get back to development in about a week or so (maybe a little less). I'll be sure to implement getrawmempool first. Cheers!

**Comment by wanglin90** [comment]
Hello，I am looking forward to it . In addtion，your github code is not same as btcd-cli4j-core-0.5.1,so please push your code to github , thank you !


wanglin20130410@gmail.com
 
From: Priidu Neemre
Date: 2016-01-18 15:33
To: priiduneemre/btcd-cli4j
CC: wanglin90
Subject: Re: [btcd-cli4j] getrawmempool (#2)
Hi, yes, I am aware that some of the JSON-RPC API is still unsupported by this library. I am planning to get back to development in about a week or so (maybe a little less). I'll be sure to implement getrawmempool first. Cheers!

**Comment by priiduneemre** [comment]
Support for the `getrawmempool` command (via JSON-RPC API) has been added to [master](https://github.com/priiduneemre/btcd-cli4j/tree/master) & will also be included in the next `.jar` release of `btcd-cli4j-core`. 

Meanwhile, you can either use the `master` code directly or (alternatively) clone the repository and create your own release using Maven (the `pom.xml` files are pretty vanilla for this project, so packaging should work out-of-the-box).

**Comment by wanglin90** [comment]
Thank you so much !



wanglin20130410@gmail.com
 
From: Priidu Neemre
Date: 2016-02-17 02:54
To: priiduneemre/btcd-cli4j
CC: wanglin90
Subject: Re: [btcd-cli4j] Add support for the 'getrawmempool' RPC (#2)
Support for the getrawmempool command (via JSON-RPC API) has been added to master & will also be included in the next .jar release of btcd-cli4j-core. 
Meanwhile, you can either use the master code directly or (alternatively) clone the repository and create your own release using Maven (the pom.xml files are pretty vanilla for this project, so packaging should work out-of-the-box).
